import type { Metadata } from "next";

// import { San francisco Pro Display } from "next/font/google";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "intensive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
