
type Company = {
  company: String;
  totalShares: String;
  totalReturn: any;
  logo: any;
  chart: any;
};


export const companies: Company[] = [
  {
    company: "Apple",
    totalShares: "$543.87",
    totalReturn: "-1.56%",
    logo: "/Ellipse 361.svg",
    chart: "/Frame 106.svg",
  },
  {
    company: "Meta",
    totalShares: "$956.43",
    totalReturn: "-0.16%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 107.svg",
  },
  {
    company: "Microsoft",
    totalShares: "$1,543.23",
    totalReturn: "+1.01%",
    logo: "/Ellipse 363.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Google",
    totalShares: "$2,073.37",
    totalReturn: "+2.41%",
    logo: "/Ellipse 364.svg",
    chart: "/Frame 109.svg",
  },
  {
    company: "Ubisoft",
    totalShares: "$173.02",
    totalReturn: "-12.87%",
    logo: "/Ellipse 365.svg",
    chart: "/Frame 110.svg",
  },
  {
    company: "Adobe",
    totalShares: "$1,863,23",
    totalReturn: "-0.53",
    logo: "/Ellipse 366.svg",
    chart: "/Frame 111.svg",
  },
  {
    company: "Amazon",
    totalShares: "$1,923,35",
    totalReturn: "+1.73",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Facebook",
    totalShares: "$1,732.23",
    totalReturn: "+0.32%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
  {
    company: "Netflix",
    totalShares: "$1,847.23",
    totalReturn: "+0.69%",
    logo: "/Ellipse 362.svg",
    chart: "/Frame 108.svg",
  },
];
