type Transaction = {
  logo: any;
  company: String;
  abbreviation: String | number;
  totalReturn: any;
  task: String;
  data: any;
};

export const transactions: Transaction[] = [
  {
    logo: "./Ellipse 367.svg",
    company: "Tesla",
    abbreviation: "TSLA",
    totalReturn: "+$2,675.34",
    task: "Completed",
    data: "16 Sep, 2023",
  },
  {
    logo: "./Ellipse 368.svg",
    company: "Netflix",
    abbreviation: "NET",
    totalReturn: "+$1.655.14",
    task: "Completed",
    data: "15 Sep, 2023",
  },
  {
    logo: "./Ellipse 369.svg",
    company: "Apple",
    abbreviation: "APP",
    totalReturn: "+$7,856.76",
    task: "Completed",
    data: "15 Sep, 2023",
  },
  {
    logo: "./Ellipse 370.svg",
    company: "Microsoft",
    abbreviation: "MICR",
    totalReturn: "+$3,915.84",
    task: "Completed",
    data: "15 Sep, 2023",
  },
  {
    logo: "./Ellipse 371.svg",
    company: "Ubisoft",
    abbreviation: "UBI",
    totalReturn: "+$205.14",
    task: "Completed",
    data: "14 Sep, 2023",
  },
  {
    logo: "./Ellipse 372.svg",
    company: "Adobe",
    abbreviation: "ADOB",
    totalReturn: "+$1,0005.94",
    task: "Completed",
    data: "14 Sep, 2023",
  },
  {
    logo: "./Ellipse 373.svg",
    company: "Google",
    abbreviation: "GOOGLE",
    totalReturn: "+$175.09",
    task: "Completed",
    data: "14 Sep, 2023",
  },
  {
    logo: "./Ellipse 374.svg",
    company: "Meta",
    abbreviation: "META",
    totalReturn: "+$8,472.19",
    task: "Completed",
    data: "14 Sep, 2023",
  },
  {
    logo: "./Ellipse 375.svg",
    company: "Samsung",
    abbreviation: "SAMS",
    totalReturn: "+$4,775.94",
    task: "Completed",
    data: "13 Sep, 2023",
  },
  {
    logo: "./Ellipse 376.svg",
    company: "Xiaomi",
    abbreviation: "XIO",
    totalReturn: "+$2,001.22",
    task: "Completed",
    data: "13 Sep, 2023",
  },
  {
    logo: "./Ellipse 377.svg",
    company: "Tiktok",
    abbreviation: "TKT",
    totalReturn: "+$615.39",
    task: "Completed",
    data: "13 Sep, 2023",
  },
  {
    logo: "./Ellipse 378.svg",
    company: "Kaspi",
    abbreviation: "KSI",
    totalReturn: "+$8,154.53",
    task: "Completed",
    data: "12 Sep, 2023",
  },
  {
    logo: "./Ellipse 379.svg",
    company: "Halyk Bank",
    abbreviation: "HBN",
    totalReturn: "+$1,764.21",
    task: "Completed",
    data: "12 Sep, 2023",
  },
  {
    logo: "./Ellipse 380.svg",
    company: "Figma",
    abbreviation: "FIGMA",
    totalReturn: "+$1,347.67",
    task: "Completed",
    data: "12 Sep, 2023",
  },
  {
    logo: "./Ellipse 368.svg",
    company: "Netflix",
    abbreviation: "NET",
    totalReturn: "+$1.655.14",
    task: "Completed",
    data: "15 Sep, 2023",
  },
  {
    logo: "./Ellipse 368.svg",
    company: "Netflix",
    abbreviation: "NET",
    totalReturn: "+$1.655.14",
    task: "Completed",
    data: "15 Sep, 2023",
  },
  {
    logo: "./Ellipse 368.svg",
    company: "Netflix",
    abbreviation: "NET",
    totalReturn: "+$1.655.14",
    task: "Completed",
    data: "15 Sep, 2023",
  },
  {
    logo: "./Ellipse 368.svg",
    company: "Netflix",
    abbreviation: "NET",
    totalReturn: "+$1.655.14",
    task: "Completed",
    data: "15 Sep, 2023",
  },
];
